-- 创建相册表
CREATE TABLE IF NOT EXISTS `albums` (
    `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '相册ID',
    `name` VARCHAR(100) NOT NULL COMMENT '相册名称',
    `cover_url` VARCHAR(500) COMMENT '封面图片URL',
    `photo_count` INT DEFAULT 0 COMMENT '照片数量',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='相册表';

-- 更新照片表，添加新字段
ALTER TABLE `photo` ADD COLUMN IF NOT EXISTS `caption` VARCHAR(500) COMMENT '配文';
ALTER TABLE `photo` ADD COLUMN IF NOT EXISTS `shoot_time` DATETIME COMMENT '拍摄时间';
ALTER TABLE `photo` ADD COLUMN IF NOT EXISTS `album_id` BIGINT COMMENT '所属相册ID';
ALTER TABLE `photo` ADD COLUMN IF NOT EXISTS `album_name` VARCHAR(100) COMMENT '所属相册名称';
ALTER TABLE `photo` ADD COLUMN IF NOT EXISTS `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- 添加外键约束
ALTER TABLE `photo` ADD CONSTRAINT IF NOT EXISTS `fk_photo_album` FOREIGN KEY (`album_id`) REFERENCES `albums`(`id`) ON DELETE SET NULL;
